services:
  question-backend:
    image: question-backend:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: question-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://question-db:3306/question?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: mysql
      SPRING_DATASOURCE_PASSWORD: fdsgdf12XXX2341
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.MySQL8Dialect
    ports:
      - "8021:8021"
    depends_on:
      - mysql
    networks:
      - question-net
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: question-db
    ports:
      - "3312:3306"
    environment:
      MYSQL_USER: mysql
      MYSQL_ROOT_PASSWORD: fdsgdf12XXX2341
      MYSQL_PASSWORD: fdsgdf12XXX2341
      MYSQL_DATABASE: question
    volumes:
      - question-mysql-data:/var/lib/mysql
    networks:
      - question-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - question-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - question-net

networks:
  question-net:
    name: question-net

volumes:
  question-mysql-data:
