name: Java CI with Maven

on:
  push:
    branches:
      - "**"  # Match all branches
  pull_request:
    branches:
      - "**"  # Match all branches

jobs:
  build:

    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      - name: Execute update.sh on VPS
        if: github.ref == 'refs/heads/dev'  # Only execute on the dev branch
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /srv/qrcode/qr-backend &&
            sudo git pull && sudo docker compose down && sudo docker compose up -d --build

      - name: Health Check
        if: github.ref == 'refs/heads/dev'  # Only execute on the dev branch
        run: |
          sleep 10 # wait for the server to start
          response=$(curl --write-out '%{http_code}' --silent --output /dev/null https://qrcode-backend.dev.codepred.pl/)
          if [ "$response" -ne 200 ]; then
            echo "Health check failed with status code $response"
            exit 1
          fi
          echo "Health check succeeded with status code $response"
