name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Test with Maven
        run: |
          cd backend  # Move to the backend directory
          mvn clean install -Ptest

      - name: Generate dependency graph
        run: |
          cd backend  # Move to the backend directory
          mvn dependency:tree > dependency-graph.txt

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
        with:
          dependency-file: backend/dependency-graph.txt

      - name: Execute update.sh on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /srv/vocabulary-learning-tool &&
            sudo ./update.sh

      - name: Health Check
        run: |
          sleep 10 # wait for the server to start
          response=$(curl --write-out '%{https_code}' --silent --output /dev/null https://quiz-backend.dev.codepred.pl/api/version)
          if [ "$response" -ne 200 ]; then
            echo "Health check failed with status code $response"
            exit 1
          fi
          echo "Health check succeeded with status code $response"
